"""Inject a visible AI attribution into human-facing deliverables.

The module never alters machine-readable research artifacts. Watermark failures
fall back to a byte-for-byte copy so publishing remains non-blocking.
"""

from __future__ import annotations

import logging
import os
import shutil
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)

WATERMARK_TEXT: str = "Generated by AI, please verify"


def _copy_fallback(source_path: Path, target_path: Path) -> None:
    shutil.copy2(source_path, target_path)


def _copy_metadata(source_path: Path, target_path: Path) -> None:
    try:
        shutil.copystat(source_path, target_path)
    except Exception:
        pass


def _has_watermark_text(content: str) -> bool:
    return WATERMARK_TEXT in content


def _write_text(
    source_path: Path, target_path: Path, suffix: str, ensure_newline: bool
) -> None:
    content = source_path.read_text(encoding="utf-8")
    if _has_watermark_text(content):
        _copy_fallback(source_path, target_path)
        return
    if ensure_newline and content and not content.endswith("\n"):
        content += "\n"
    target_path.write_text(content + suffix, encoding="utf-8")
    _copy_metadata(source_path, target_path)


def _watermark_markdown(source_path: Path, target_path: Path) -> None:
    # Horizontal rule + italic line mimics the small-gray visual style.
    _write_text(
        source_path,
        target_path,
        suffix="\n\n---\n\n*" + WATERMARK_TEXT + "*\n",
        ensure_newline=False,
    )


def _watermark_text(source_path: Path, target_path: Path) -> None:
    _write_text(
        source_path,
        target_path,
        suffix="\n\n" + WATERMARK_TEXT + "\n",
        ensure_newline=False,
    )


# Candidate TrueType fonts, CJK first (needed to render the Chinese watermark),
# then Latin fallbacks (render tofu for CJK glyphs but never crash). On systems
# with a CJK font installed (e.g. Noto/WQY), the watermark renders correctly;
# otherwise it degrades to boxes plus the embedded PNG text chunk for machines.
_FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc",
    "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/google-noto-cjk/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/droid/DroidSansFallback.ttf",
    "/usr/share/fonts/droid/DroidSansFallback.ttf",
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/STHeiti Light.ttc",
    "C:/Windows/Fonts/msyh.ttc",
    "C:/Windows/Fonts/simhei.ttf",
    "/usr/share/fonts/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]


def _load_font(size: int):
    """Load a TrueType font, preferring CJK-capable ones. Never raises."""
    from PIL import ImageFont

    for path in _FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue
    try:
        return ImageFont.load_default(size)
    except TypeError:  # older Pillow without size arg
        return ImageFont.load_default()
    except Exception:
        return None


def _draw_watermark_on_image(img):
    from PIL import Image, ImageDraw

    img = img.convert("RGBA")
    width, height = img.size
    font_size = max(11, min(width, height) // 30)
    font = _load_font(font_size)
    overlay = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    text = WATERMARK_TEXT
    try:
        if font is not None:
            bbox = draw.textbbox((0, 0), text, font=font)
            text_w = bbox[2] - bbox[0]
            text_h = bbox[3] - bbox[1]
        else:
            raise RuntimeError("no font available")
    except Exception:
        text_w = max(1, font_size * len(text) // 2)
        text_h = font_size
    margin = 8
    x = max(0, width - text_w - margin)
    y = max(0, height - text_h - margin)
    # (153,153,153) approximates #999; alpha 180 approximates opacity 0.7.
    draw.text((x, y), text, font=font, fill=(153, 153, 153, 180))
    return Image.alpha_composite(img, overlay)


def _watermark_png(source_path: Path, target_path: Path) -> None:
    from PIL import Image
    from PIL.PngImagePlugin import PngInfo

    with Image.open(source_path) as im:
        # Idempotency: detect a previously embedded text chunk (reliable).
        if im.info.get("_watermark") == WATERMARK_TEXT:
            _copy_fallback(source_path, target_path)
            return
        result = _draw_watermark_on_image(im)
    pnginfo = PngInfo()
    pnginfo.add_text("_watermark", WATERMARK_TEXT)
    result.save(str(target_path), format="PNG", pnginfo=pnginfo)
    _copy_metadata(source_path, target_path)


def _watermark_jpeg(source_path: Path, target_path: Path) -> None:
    from PIL import Image

    with Image.open(source_path) as im:
        result = _draw_watermark_on_image(im).convert("RGB")
    result.save(str(target_path), format="JPEG", quality=95)
    _copy_metadata(source_path, target_path)


def _watermark_xlsx(source_path: Path, target_path: Path) -> None:
    from openpyxl import load_workbook
    from openpyxl.styles import Font

def _watermark_pdf(source_path: Path, target_path: Path) -> None:
    try:
        from pypdf import PdfReader, PdfWriter
        from reportlab.lib.colors import Color
        from reportlab.lib.pagesizes import landscape, portrait
        from reportlab.pdfbase.pdfmetrics import stringWidth
        from reportlab.pdfgen import canvas
    except ImportError:
        logger.warning("PDF watermark skipped (deps unavailable): %s", source_path)
        _copy_fallback(source_path, target_path)
        return

    try:
        reader = PdfReader(str(source_path))
        writer = PdfWriter()
        for page in reader.pages:
            width = float(page.mediabox.width)
            height = float(page.mediabox.height)
            page_size = landscape((width, height)) if width > height else portrait((width, height))
            buffer = tempfile.SpooledTemporaryFile()
            overlay = canvas.Canvas(buffer, pagesize=page_size)
            font_size = max(7, min(width, height) / 70)
            overlay.setFont("Helvetica", font_size)
            overlay.setFillColor(Color(0.6, 0.6, 0.6, alpha=0.7))
            text_width = stringWidth(WATERMARK_TEXT, "Helvetica", font_size)
            overlay.drawString(max(8, width - text_width - 8), 8, WATERMARK_TEXT)
            overlay.save()
            buffer.seek(0)
            page.merge_page(PdfReader(buffer).pages[0])
            writer.add_page(page)
        writer.add_metadata({"/Watermark": WATERMARK_TEXT})
        with target_path.open("wb") as handle:
            writer.write(handle)
        _copy_metadata(source_path, target_path)
    except Exception:
        logger.warning("PDF watermark skipped (render failed): %s", source_path)
        _copy_fallback(source_path, target_path)


_HANDLERS = {
    ".md": _watermark_markdown,
    ".markdown": _watermark_markdown,
    ".txt": _watermark_text,
    ".png": _watermark_png,
    ".jpg": _watermark_jpeg,
    ".jpeg": _watermark_jpeg,
}


def apply_watermark(source_path: Path, target_path: Path) -> Path:
    """Inject a watermark from ``source_path`` into ``target_path`` by extension.

    Unsupported types fall back to ``shutil.copy2``. Any watermarking error falls
    back to a plain copy so the deliverable pipeline is never interrupted.
    Returns ``target_path``.
    """
    source_path = Path(source_path)
    target_path = Path(target_path)
    ext = source_path.suffix.lower()
    try:
        if ext == ".pdf":
            _watermark_pdf(source_path, target_path)
        else:
            handler = _HANDLERS.get(ext)
            if handler is None:
                _copy_fallback(source_path, target_path)
            else:
                handler(source_path, target_path)
    except Exception as e:
        logger.warning("Watermark failed for %s, fallback to copy: %s", source_path, e)
        try:
            _copy_fallback(source_path, target_path)
        except Exception as copy_err:
            logger.warning("Copy fallback also failed for %s: %s", source_path, copy_err)
            raise
    return target_path


def apply_watermark_inplace(path: Path) -> None:
    """Inject a watermark in place via a temp file then ``os.replace``."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    fd, tmp_name = tempfile.mkstemp(suffix=path.suffix, dir=str(path.parent))
    tmp_path = Path(tmp_name)
    try:
        os.close(fd)
        apply_watermark(path, tmp_path)
        os.replace(tmp_path, path)
    except Exception:
        if tmp_path.exists():
            try:
                tmp_path.unlink()
            except Exception:
                pass
        raise
