import type { ChatResponsePayload, ThinkingStep } from '@/types';

/**
 * Chat-run SSE event vocabulary — single source of truth on the frontend.
 *
 * Mirrors the backend registry `app/services/chat_run_events.py`; the two
 * sides are kept honest by contract tests on both ends:
 * - backend: `app/tests/chat/test_chat_run_event_schema.py`
 * - frontend: this module's vitest consumes `chatRunEvents.canonical.json`,
 *   regenerated by `scripts/export_chat_run_event_schema.py` whenever the
 *   backend registry changes (drift = failing test on the stale side).
 */
export type ChatStreamEvent =
    | { type: 'start' }
    | { type: 'delta'; content: string }
    | { type: 'final'; payload: ChatResponsePayload }
    | { type: 'job_update'; payload: Record<string, any> }
    | { type: 'error'; message?: string; error_type?: string }
    | { type: 'thinking_step'; step: ThinkingStep }
    | { type: 'thinking_delta'; iteration: number; delta: string }
    | { type: 'reasoning_delta'; iteration: number; delta: string }
    | { type: 'progress_status'; phase?: string; label?: string; details?: string | null; iteration?: number | null; tool?: string | null; status?: string | null }
    | { type: 'control_ack'; job_id?: string; available?: boolean; paused?: boolean; action?: string | null }
    | { type: 'tool_output'; tool?: string; stream?: string; content?: string; iteration?: number | null }
    | {
        type: 'artifact';
        path?: string;
        extension?: string;
        source_tool?: string;
        iteration?: number;
        display_name?: string;
        mime_family?: string;
        origin?: string;
        tracking_id?: string | null;
      }
    | { type: 'steer_ack'; message?: string; iteration?: number };

export const CHAT_RUN_EVENT_TYPES = [
    'start',
    'delta',
    'final',
    'job_update',
    'error',
    'thinking_step',
    'thinking_delta',
    'reasoning_delta',
    'progress_status',
    'control_ack',
    'tool_output',
    'artifact',
    'steer_ack',
] as const;

export type ChatRunEventType = (typeof CHAT_RUN_EVENT_TYPES)[number];

const isPlainObject = (value: unknown): value is Record<string, unknown> =>
    typeof value === 'object' && value !== null && !Array.isArray(value);

/**
 * Fail-open contract check: returns null when valid, otherwise a short
 * human-readable reason. Mirrors the backend `validate_chat_run_event`
 * (required core fields only; extra keys are allowed to evolve freely).
 * Used at the SSE parse boundary for drift telemetry — never blocks rendering.
 */
export const validateChatRunEvent = (payload: unknown): string | null => {
    if (!isPlainObject(payload)) {
        return 'event payload is not an object';
    }
    const type = payload.type;
    if (typeof type !== 'string') {
        return 'missing event type';
    }
    if (!(CHAT_RUN_EVENT_TYPES as readonly string[]).includes(type)) {
        return `unknown event type '${type}'`;
    }
    switch (type as ChatRunEventType) {
        case 'delta':
            return typeof payload.content === 'string' ? null : 'delta.content must be a string';
        case 'final':
        case 'job_update':
            return isPlainObject(payload.payload) ? null : `${type}.payload must be an object`;
        case 'thinking_step':
            return isPlainObject(payload.step) ? null : 'thinking_step.step must be an object';
        case 'thinking_delta':
        case 'reasoning_delta':
            if (typeof payload.iteration !== 'number') {
                return `${type}.iteration must be a number`;
            }
            if (typeof payload.delta !== 'string') {
                return `${type}.delta must be a string`;
            }
            return null;
        default:
            return null;
    }
};
