"""Plan decomposition prompts."""

from .merge_similarity import (
    BATCH_SIMILARITY_SYSTEM,
    BATCH_SIMILARITY_USER,
    MERGE_SIMILARITY_SYSTEM,
    MERGE_SIMILARITY_USER,
)

__all__ = [
    "BATCH_SIMILARITY_SYSTEM",
    "BATCH_SIMILARITY_USER",
    "MERGE_SIMILARITY_SYSTEM",
    "MERGE_SIMILARITY_USER",
]
