"""
Interpreter Prompt Templates
"""

from .coder_prompt import (
    CODER_SYSTEM_PROMPT,
    CODER_USER_PROMPT_TEMPLATE,
    CODER_FIX_PROMPT_TEMPLATE,
)
from .experiment_design import (
    EXPERIMENT_DESIGN_SYSTEM,
    EXPERIMENT_DESIGN_USER,
)
from .task_executer import (
    TASK_TYPE_SYSTEM_PROMPT,
    TASK_TYPE_USER_PROMPT_TEMPLATE,
    TEXT_TASK_PROMPT_TEMPLATE,
    INFO_GATHERING_SYSTEM_PROMPT,
    INFO_GATHERING_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "CODER_SYSTEM_PROMPT",
    "CODER_USER_PROMPT_TEMPLATE",
    "CODER_FIX_PROMPT_TEMPLATE",
    "EXPERIMENT_DESIGN_SYSTEM",
    "EXPERIMENT_DESIGN_USER",
    "TASK_TYPE_SYSTEM_PROMPT",
    "TASK_TYPE_USER_PROMPT_TEMPLATE",
    "TEXT_TASK_PROMPT_TEMPLATE",
    "INFO_GATHERING_SYSTEM_PROMPT",
    "INFO_GATHERING_USER_PROMPT_TEMPLATE",
]
